### ISSUE TITLE
Bug report: Detected blocking call

### ISSUE THREAD

**Issue by Elarion245** [PhoenixR49/hass-huggingchat-conversation#16]
**Describe the bug**
Version 1.3.6 produces the following log entry:
```
Logger: homeassistant.util.loop
Quelle: util/loop.py:136
Erstmals aufgetreten: 12:21:28 (2 Vorkommnisse)
Zuletzt protokolliert: 12:21:28

    Detected blocking call to listdir with args ('./config/custom_components/huggingchat_conversation/cookies_snapshot/',) inside the event loop by custom integration 'huggingchat_conversation' at custom_components/huggingchat_conversation/__init__.py, line 106: cookies = sign.loadCookiesFromDir(cookie_path_dir) (offender: /usr/local/lib/python3.12/site-packages/hugchat/login.py, line 212: files = os.listdir(cookie_dir_path)), please create a bug report at https://github.com/PhoenixR49/hass-huggingchat-conversation/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response await func(hass, connection, msg) File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 251, in websocket_run run_task = hass.async_create_task(pipeline_input.execute()) File "/usr/src/homeassistant/homeassistant/core.py", line 819, in async_create_task return self.async_create_task_internal(target, name, eager_start) File "/usr/src/homeassistant/homeassistant/core.py", line 841, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1412, in execute tts_input = await self.run.recognize_intent( File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1017, in recognize_intent conversation_result = await conversation.async_converse( File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse result = await method(conversation_input) File "/config/custom_components/huggingchat_conversation/__init__.py", line 106, in async_process cookies = sign.loadCookiesFromDir(cookie_path_dir)
    Detected blocking call to open with args ('./config/custom_components/huggingchat_conversation/cookies_snapshot/Chad-kroeger@gmx.net.json', 'r') inside the event loop by custom integration 'huggingchat_conversation' at custom_components/huggingchat_conversation/__init__.py, line 106: cookies = sign.loadCookiesFromDir(cookie_path_dir) (offender: /usr/local/lib/python3.12/site-packages/hugchat/login.py, line 95: with open(cookie_path, "r", encoding="utf-8") as f:), please create a bug report at https://github.com/PhoenixR49/hass-huggingchat-conversation/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 28, in _handle_async_response await func(hass, connection, msg) File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/websocket_api.py", line 251, in websocket_run run_task = hass.async_create_task(pipeline_input.execute()) File "/usr/src/homeassistant/homeassistant/core.py", line 819, in async_create_task return self.async_create_task_internal(target, name, eager_start) File "/usr/src/homeassistant/homeassistant/core.py", line 841, in async_create_task_internal task = create_eager_task(target, name=name, loop=self.loop) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1412, in execute tts_input = await self.run.recognize_intent( File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1017, in recognize_intent conversation_result = await conversation.async_converse( File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse result = await method(conversation_input) File "/config/custom_components/huggingchat_conversation/__init__.py", line 106, in async_process cookies = sign.loadCookiesFromDir(cookie_path_dir)

```

**To Reproduce**
Install 1.3.6 and reboot HA

**Expected behavior**
No log entry reporting a warning or error

**Environment:**
 - Home Assistant version 2024.11
 - Version 1.3.6

**Comment by Elarion245** [comment]
If I untick "assistant" I can actually start some conversation, but not control anything. So it seems that this may not be a bug, but just a matter of missing documentation?
