### ISSUE TITLE
Bug report: wrong conversation id

### ISSUE THREAD

**Issue by Elarion245** [PhoenixR49/hass-huggingchat-conversation#18]
**Describe the bug**
`Logger: homeassistant.components.assist_pipeline.pipeline
Quelle: components/assist_pipeline/pipeline.py:1017
Integration: Assist pipeline (Dokumentation, Probleme)
Erstmals aufgetreten: 08:19:27 (2 Vorkommnisse)
Zuletzt protokolliert: 08:19:40

Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1017, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huggingchat_conversation/__init__.py", line 190, in async_process
    await self.hass.async_add_executor_job(chatbot.change_conversation, info)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hugchat/hugchat.py", line 257, in change_conversation
    raise exceptions.InvalidConversationIDError(
hugchat.exceptions.InvalidConversationIDError: Invalid conversation id, not in conversation list.`

**To Reproduce**
Install 1.3.7 and use. After the upgrade it worked exactly one and then I received the error. Not working since then, also not with assist enabled l. 

**Expected behavior**
Working Assist

**Environment:**
 - Home Assistant 2024.11
 - Version 1.3.7

**Comment by Invernomut0** [comment]
Same here:

**ENV:**
Core: 2024.11.3
Supervisor: 2024.11.4
Operating System: 13.2
Frontend: 20241106.2
Huggingface 1.3.7

**ERROR:**
Unexpected error during intent recognition
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1017, in recognize_intent
    conversation_result = await conversation.async_converse(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 110, in async_converse
    result = await method(conversation_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huggingchat_conversation/__init__.py", line 190, in async_process
    await self.hass.async_add_executor_job(chatbot.change_conversation, info)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hugchat/hugchat.py", line 257, in change_conversation
    raise exceptions.InvalidConversationIDError(
hugchat.exceptions.InvalidConversationIDError: Invalid conversation id, not in conversation list.
