### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by MrAvana** [PhoenixR49/hass-huggingchat-conversation#7]
I keep getting the error: "Sorry I have a problem taking to HuggingChat server".

Here's the log: 

`2024-06-15 06:42:44.006 ERROR (SyncWorker_3) [root] No `type` found in response: {'message': 'An error occurred', 'errorId': '7297ebf8-7557-4cf4-987d-62ee154af2fa'}
2024-06-15 06:43:02.887 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'huggingchat_conversation' at custom_components/huggingchat_conversation/__init__.py, line 106: cookies = sign.loadCookiesFromDir(cookie_path_dir) (offender: /usr/local/lib/python3.12/site-packages/hugchat/login.py, line 95: with open(cookie_path, "r", encoding="utf-8") as f:), please create a bug report at https://github.com/PhoenixR49/hass-huggingchat-conversation/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1414, in execute
    tts_input = await self.run.recognize_intent(
  File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 994, in recognize_intent
    conversation_result = await conversation.async_converse(
  File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse
    result = await method(conversation_input)
  File "/config/custom_components/huggingchat_conversation/__init__.py", line 106, in async_process
    cookies = sign.loadCookiesFromDir(cookie_path_dir)`

**Comment by PhoenixR49** [comment]
I just fixed the problem, it came from the bug on an old version of the `hugchat` module. I've just updated it and it works.

Update the integration to fix the problem.
